### ISSUE TITLE
Баг - отображение шорткода cf7 в теме Savoy (решение)

### ISSUE THREAD

**Issue by youtube666** [artikus11/art-woocommerce-order-one-click#20]
решение: по адресу wp-content\themes\savoy\includes\visual-composer
открыть файл elements-config.php и удалить или закомментировать код:

`function nm_vc_remove_plugin_elements() {
	vc_remove_element( 'contact-form-7' );
	}
 	add_action( 'vc_after_set_mode', 'nm_vc_remove_plugin_elements', 100 );`

**Comment by artikus11** [comment]
Хм, ну так себе решение. Тема обновилась и все слетело. Тогда через фильтры надо менять или хотя бы через дочерку
