### ISSUE TITLE
Поп-ап

### ISSUE THREAD

**Issue by kiev1979** [artikus11/art-woocommerce-order-one-click#28]
Сделать возможность кастомизации окна попап. Сейчас выглядит просто ужасно. И сделать выбор не только cf-7, а еще топовых форм.

**Comment by artikus11** [comment]
@kiev1979 кастомизация окна будет в отдельном аддоне. Осталось только понять как будет не ужасно? Пример можете привести?

**Comment by kiev1979** [comment]
Да возьмите топовые попап любой и у них можно глянуть два три шаблона и так и сделать. Хватит с головой. Их просто легче в разы будет докручивать.

**Comment by kiev1979** [comment]
http://joxi.ru/5md5Ppph3MaEW2
вот у этих есть шаблоны. самые обычные. можно такие же сделать

**Comment by artikus11** [comment]
Фильтр awooc_popup_setting позволяет изменить внешний вид окна
