### ISSUE TITLE
Подлипание кнопки к количесвту товара.

### ISSUE THREAD

**Issue by Asurgor** [artikus11/art-woocommerce-order-one-click#33]
![Screenshot_1](https://user-images.githubusercontent.com/54076345/64533150-9e01b300-d31b-11e9-9088-c34852fbe840.png)
Доброго времени!
Благодарствую за труды, хорошая работа, полезная вещь. У меня вопросик к вам, из раздела "песочницы" безусловно, но всеже.
Подскажите пожалуйста, где можно подправить CSS, что бы кнопка не "подлипала", пару тройку пикселей добавить, отодвинуть ниже. Это у меня в теме WP WoonderShop (Jungles)(https://www.proteusthemes.com)
Спасибо за работу и удачи!

Так на мобильной версии.
![Screenshot_20190909-162206](https://user-images.githubusercontent.com/54076345/64535246-96440d80-d31f-11e9-947d-d5a711b588f4.jpg)

**Comment by artikus11** [comment]
Доброго! Стили просто добавьте. Вот тут посмотрите https://wpruse.ru/my-plugins/art-woocommerce-order-one-click/#kak-izmenit-vneshnij-vid-knopki есть пример как можно стили добавить. Ну и добавлять лучше через кастомайзер

**Comment by Asurgor** [comment]
Доброго времени! Благодарю вас, как разработчика за быстрый отклик.
Однако, в двух словах, суть в том, что я смотрел часть кода на вашем сайте,
для правки рассположения кнопки "Заказ в один клик". И порбовал править в
дочерней теме. Но там сложность в том, что у меня "дочерняя-дочерней"...) И
в редакторе не подсвечивается. Потому, прошу вас подсказать место правки
кнопки именно в ваших файлах. Надеюсь они унаследуются в моей теме. За
ранее благодарен. С ув. Сергей.

Сергей Жанклен

пн, 9 сент. 2019 г., 16:36 Artem Abramovich <notifications@github.com>:

**Comment by artikus11** [comment]
@Asurgor не бывает дочки от дочки. Такого функционала нет в ВП. А вносить изменения в файлы тему - плохая идея, завтра выкачу апдейт и у вас все слетит. Но если сильно надо то все стили тут сидят https://github.com/artikus11/art-woocommerce-order-one-click/blob/master/assets/css/admin-style.min.css

Вам не нужна дочерняя тема. Вам нужен кастомайзер раздел дополнительные стили в нем
