### ISSUE TITLE
Если отправлять форму Contact Form 7 со страницы товара, то срабатывает событие 'awooc_mail_sent_trigger'

### ISSUE THREAD

**Issue by artikus11** [artikus11/art-woocommerce-order-one-click#48]
У меня на сайте, в шапке есть попап-окно с формой обратной связи. И если отправлять данные через эту форму находясь на странице товара с активной кнопкой вашего плагина "Купить в один клик", то вызывается вышеуказанное событие. Всё бы ничего, но у меня на это событие повешена цель яндекс метрики. И получается, что если человек закажет обратный звонок, находясь на странице товара, то сработает цель "Купить в один клик".

![image](https://user-images.githubusercontent.com/16116688/102123352-38766d80-3e60-11eb-99a8-d7c315e12bda.png)
![image](https://user-images.githubusercontent.com/16116688/102123395-3b715e00-3e60-11eb-80e5-b1c9d2d3bd87.png)
![image](https://user-images.githubusercontent.com/16116688/102123431-3f9d7b80-3e60-11eb-8a3b-5707b1452fcf.png)

Обратите внимание, вывод в консоль стоит на событии awooc_mail_sent_trigget. Но вывод происходит при отправке совсем из другой формы

**Comment by baxik88** [comment]
Попробуй создать разные формы и проверять id формы перед выполнением цели, таким образом можно будет понять кто откуда

**Comment by artikus11** [comment]
Не, это я для себя скопипастил, чтобы пофиксить в следующем релизе.  Так то надо что бы триггер срабатывал только на форме из окошка, а не для любой формы
