### ISSUE TITLE
Быстрый заказ твоаров из корзины

### ISSUE THREAD

**Issue by Corvus278** [artikus11/art-woocommerce-order-one-click#52]
В первую очередь, огромное спасибо за данный плагин!
У меня есть предложение, как его улучшить - добавить возможность быстрого заказа из корзины (в идеале с выбором товаров для заказа), так как это довольно распространённый кейс.
Возможно, данная функциональность уже есть, но у меня найти её не получилось

**Comment by artikus11** [comment]
Теоретически есть. Но надо проверить как это работать будет. В мини корзине же работает.

**Comment by Corvus278** [comment]
А как включить миникорзину?
Сейчас кнопка быстрого заказа в корзине не отображается, да поковыряв код плагина, я не нашёл поддержки такой функциональности

**Comment by artikus11** [comment]
На странице корзины и нет вывода, я ж говорил что теоретически  - это возможно). 

Миникорзина - это то что показывается при наведении на иконку корзины, в шапке обычно

**Comment by artikus11** [comment]
@Corvus278 я плагины свои перепутал) Этот плагин и не будет никогда работать с корзиной, так как заточен под другое. Но так умеет другой плагин https://github.com/artikus11/art-woocommerce-order-fast
