### ISSUE TITLE
Коррекция стилей / отзыв

### ISSUE THREAD

**Issue by Andreslav** [artikus11/art-woocommerce-order-one-click#56]
Артём, привет! Снова я.
Прежде всего, спасибо за плагин!

1. Предлагаю заменить [здесь](https://github.com/artikus11/art-woocommerce-order-one-click/blob/3eabec28ddcff2030833fd7fa07e70ae252a49d9/includes/class-awooc-enqueue.php#L83) 600px на calc(100vh - 2rem), чтобы контент не обрезался на узком экране (или горизонтальной ориентации):
![изображение](https://user-images.githubusercontent.com/39444579/233854900-0c93b35c-c92b-42be-b012-bf3d67c1af90.png) 
Будет так:
![изображение](https://user-images.githubusercontent.com/39444579/233855101-429403a7-1d04-4908-ab13-45b53045e0cd.png)
![изображение](https://user-images.githubusercontent.com/39444579/233855156-0f32d552-70ae-40cb-8cd6-6dd92bcb5c3e.png)

2. Лучше не использовать [свои](https://github.com/artikus11/art-woocommerce-order-one-click/blob/72d66911c45f60745f3faebef0c4872a67b8290e/assets/css/awooc-styles.css#L110) цвета, – рекомендую задействовать базовые переменные вордпресс, вроде var(--wp--preset--color--primary). Так будет больше шансов, что пользователю не придётся переопределять стиль. 

3. После установки плагина я получил следующее (при этом стили плагина перебивают уже настроенное оформление полей CF7 и кнопки с классом wp-element-button):
![изображение](https://user-images.githubusercontent.com/39444579/233856265-65bd471b-99c9-4279-b03c-efc645081f51.png) 
Если установить на чистую тему Twenty Twenty-Three, то получаю следующее:
![изображение](https://user-images.githubusercontent.com/39444579/233855893-248a2525-63e5-4cc9-90bb-e48a75add7b8.png)

В итоге, я переопределил файл стилей, чтобы добиться желаемого: удалил переопределения, уточнил разметку.

Стиль формы желательно доработать, чтобы а) она хорошо выглядела по умолчанию и б) была возможность без переопределения стилей сбросить оформление (например, удалив специальный класс у мод. окна через крючок).

**Comment by artikus11** [comment]
> Предлагаю заменить 600px на calc(100vh - 2rem), чтобы контент не обрезался на узком экране (или горизонтальной ориентации):

Это можете и сами заменить, там же фильтр для этого есть `awooc_popup_setting`

п.2 да можно и так сделать. 
Собственно, в плагине стилей практически нет, только необходимые, так как каждая тема по своему все это определяет и форму и кнопки

**Comment by Andreslav** [comment]
> Это можете и сами заменить
Так и сделал) Написал об этом, поскольку считаю, что это должно быть по умолчанию.

Артём, у меня есть желание самостоятельно внести некоторые изменения и отправить вам на слияние, но есть нюанс: без сборки проекта (если она предусмотрена..), только ручная коррекция файлов. Стоит заняться?

**Comment by artikus11** [comment]
Можете пулл реквест предложить, но с 3-й версии уже вебпак для сборки используется, так что смотрите сами. Предложите пулл реквест, а там, если не получиться, я могу сам внести изменения. 

Но это будет уже 3-я версия. Она кстати есть, в видел релиз кандидата, там много чего переделано, так что имеет смысл сначала вам ее мосмотреть

**Comment by Andreslav** [comment]
> Но это будет уже 3-я версия. Она кстати есть, в видел релиз кандидата, там много чего переделано, так что имеет смысл сначала вам ее мосмотреть

Нашёл, гляну.
